kind: Template
apiVersion: v1
metadata:
  name: asciidoctor-s2i
  labels:
    template: asciidoctor-s2i
  annotations:
    description: >-
      An asciidoctor s2i builder. All files named *.adoc will be converted.
      you need a file index.adoc as central page.
    iconClass: icon-nginx
    openshift.io/display-name: AsciiDoctor S2I Builder
    openshift.io/documentation-url: 'https://github.com/klenkes74/openshift-asciidoctor'
    openshift.io/long-description: >-
      This image is an S2I builder running on top of the centos nginx image.
    openshift.io/provider-display-name: 'Kaiserpfalz EDV-Service, Roland T. Lichti'
    openshift.io/support-url: 'https://www.kaiserpfalz-edv.de'
    tags: 'nginx,builder,cms'
    template.openshift.io/bindable: 'false'
parameters:
- name: ASCIIDOCTOR_VERSION
  displayName: Version (ASCIIDOCTOR)
  description: The version of asciidoctor used.
  required: true
  value: '2.0.9'
- name: ASCIIDOCTOR_CONFLUENCE_VERSION
  displayName: Version (ASCIIDOCTOR Confluence)
  description: The version of the confluence plugin for asciidoctor.
  required: true
  value: '0.0.2'
- name: ASCIIDOCTOR_PDF_VERSION
  displayName: Version (ASCIIDOCTOR PDF)
  description: The version of the PDF plugin for asciidoctor.
  required: true
  value: '1.5.0.alpha.17'
- name: ASCIIDOCTOR_DIAGRAM_VERSION
  displayName: Version (ASCIIDOCTOR Diagram)
  description: The version of the diagram plugin for asciidoctor.
  required: true
  value: '1.5.16'
- name: ASCIIDOCTOR_EPUB3_VERSION
  displayName: Version (EPUB3 Plugin)
  description: The version for the EPUB3 plugin for asciidoctor
  required: true
  value: '1.5.0.alpha.9'
- name: ASCIIDOCTOR_MATHEMATICAL_VERSION
  displayName: Version (Mathematical Plugin)
  description: The version of the math plugin for asciidoctor.
  required: true
  value: '0.3.0'
- name: ASCIIDOCTOR_REVEALJS_VERSION
  displayName: Version (RevealJS Plugin)
  description: The version of the RevealJS plugin for asciidoctor.
  required: true
  value: '2.0.0'
- name: GITHUB_SECRET
  displayName: GitHub WebHook Secret
  description: The BASE64 encoded GitHub WebHook Secret
  required: true
  value: dGExdmFpZjhob3AwbmVpOEhlZTU=
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      template: asciidoctor-s2i
      build: nginx-asciidoctor-base
      delete: asciidoctor-s2i
    name: nginx-asciidoctor-base
  spec:
    lookupPolicy:
      local: true
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    labels:
      build: nginx-asciidoctor-base
      template: asciidoctor-s2i
      delete: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
    name: nginx-asciidoctor-base-${ASCIIDOCTOR_VERSION}
  spec:
    failedBuildsHistoryLimit: 1
    successfulBuildsHistoryLimit: 3
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
    runPolicy: Serial
    source:
      dockerfile: |
        FROM openshift/nginx:1.12
        EXPOSE 8080
        EXPOSE 8443
        USER 0
        RUN yum install -y centos-release-scl-rh && yum install -y bash curl ca-certificates make java-1.8.0-openjdk-headless findutils inotify-tools ruby rh-ruby23 rh-ruby23-devel rh-ruby23-scldevel rh-ruby23-build ruby-devel baekmuk-ttf-fonts-common graphviz-ruby graphviz-devel graphviz python2-pygraphviz python2-pydot python-pillow python-pillow-devel libxml2-devel gcc python27-python-pip && yum clean all -y
        RUN scl enable rh-ruby23 "gem install --no-document asciidoctor:${ASCIIDOCTOR_VERSION} asciidoctor-confluence:${ASCIIDOCTOR_CONFLUENCE_VERSION} asciidoctor-diagram:${ASCIIDOCTOR_DIAGRAM_VERSION} asciimath asciidoctor-pdf:${ASCIIDOCTOR_PDF_VERSION} asciidoctor-revealjs:${ASCIIDOCTOR_REVEALJS_VERSION} coderay epubcheck:3.0.1 haml kindlegen:3.0.3 pygments.rb rake rouge slim thread_safe tilt"
        RUN scl enable pyhton27 "pip install --upgrade pip" && scl enable python27 "pip install --no-cache-dir actdiag blockdiag[pdf] nwdiag Pygments seqdiag"
        RUN mv /usr/libexec/s2i/assemble /usr/libexec/s2i/assemble-nginx && cp /tmp/src/.s2i/bin/assemble /usr/libexec/s2i/assemble
        USER 1001
        CMD /usr/libexec/s2i/usage
      type: Dockerfile
    strategy:
      dockerStrategy:
        env:
        - name: ASCIIDOCTOR_VERSION
          value: "${ASCIIDOCTOR_VERSION}"
        - name: ASCIIDOCTOR_CONFLUENCE_VERSION
          value: "${ASCIIDOCTOR_CONFLUENCE_VERSION}"
        - name: asciidoctor_pdf_version
          value: "${ASCIIDOCTOR_PDF_VERSION}"
        - name: ASCIIDOCTOR_DIAGRAM_VERSION
          value: "${ASCIIDOCTOR_DIAGRAM_VERSION}"
        - name: ASCIIDOCTOR_EPUB3_VERSION
          value: "${ASCIIDOCTOR_EPUB3_VERSION}"
        - name: ASCIIDOCTOR_MATHEMATICAL_VERSION
          value: "${ASCIIDOCTOR_MATHEMATICAL_VERSION}"
        - name: ASCIIDOCTOR_REVEALJS_VERSION
          value: "${ASCIIDOCTOR_REVEALJS_VERSION}"
        from:
          kind: ImageStreamTag
          name: nginx:1.12
          namespace: openshift
      type: Docker
    output:
      to:
        kind: ImageStreamTag
        name: 'nginx-asciidoctor-base:${ASCIIDOCTOR_VERSION}'
    triggers:
    - type: GitHub
      github:
        secretReference:
          name: asciidoctor-s2i
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nginx@sha256:e24f944339b6cd48ba74f6950d2e32e003c156d4e701ad4f4e5b3b7ac6b73230
      type: ImageChange
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    annotations:
      description: The ASCIIDOC builder based on s2i
      template.alpha.openshift.io/wait-for-ready: 'true'
    labels:
      template: asciidoctor-s2i
      delete: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
    name: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
  spec:
    completionDeadlineSeconds: 600
    failedBuildsHistoryLimit: 1
    output:
      imageLabels:
        - name: io.k8s.display-name
          value: ASCIIdoc S2I Builder
        - name: io.k8s.description
          value: >-
            The ASCIIDOC S2I Builder (based on nginx on centos)
        - name: io.openshift.s2i.scripts-url
          value: 'image:///usr/libexec/s2i'
        - name: io.s2i.scripts-url
          value: 'image:///usr/libexec/s2i'
        - name: io.openshift.tags
          value: 'builder,asciidoc,nginx'
        - name: template
          value: asciidoc-s2i
        - name: io.openshift.expose-services
          value: '8080:http'
      to:
        kind: ImageStreamTag
        name: 'asciidoctor-s2i:${ASCIIDOCTOR_VERSION}'
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: 'https://github.com/klenkes74/openshift-asciidoctor.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: 'nginx-asciidoctor-base:${ASCIIDOCTOR_VERSION}'
          namespace: dev-images
      type: Source
    successfulBuildsHistoryLimit: 2
    triggers:
      - imageChange:
        type: ImageChange
      - type: ConfigChange
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      template: asciidoctor-s2i
      delete: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
    name: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
  spec:
    lookupPolicy:
      local: true
- kind: Secret
  apiVersion: v1
  metadata:
    name: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
    labels:
      template: asciidoctor-s2i
      delete: asciidoctor-s2i-${ASCIIDOCTOR_VERSION}
  type: Opaque
  data:
    WebHookSecretKey: ${GITHUB_SECRET}
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    labels:
      template: asciidoctor-s2i
    name: asciidoctor-s2i
  spec:
    lookupPolicy:
      local: true
