apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    description: The ASCIIDOC builder based on s2i
    template.alpha.openshift.io/wait-for-ready: 'true'
  labels:
    template: asciidoctor-s2i
  name: asciidoctor-s2i
spec:
  completionDeadlineSeconds: 600
  failedBuildsHistoryLimit: 1
  output:
    imageLabels:
      - name: io.k8s.display-name
        value: ASCIIdoc S2I Builder
      - name: io.k8s.description
        value: >-
          The ASCIIDOC S2I Builder (based on nginx on centos)
      - name: io.openshift.s2i.scripts-url
        value: 'image:///usr/libexec/s2i'
      - name: io.s2i.scripts-url
        value: 'image:///usr/libexec/s2i'
      - name: io.openshift.tags
        value: 'builder,asciidoc,nginx'
      - name: template
        value: asciidoc-s2i
      - name: io.openshift.expose-services
        value: '8080:http'
    to:
      kind: ImageStreamTag
      name: 'asciidoctor-s2i:2.0.9'
  resources:
    limits:
      cpu: 250m
      memory: 128Mi
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: 'https://github.com/klenkes74/openshift-asciidoctor.git'
    type: Git
  env:
  - name: ASCIIDOCTOR_VERSION
    value: '2.0.9'
  - name: ASCIIDOCTOR_CONFLUENCE_VERSION
    value: '0.0.2'
  - name: asciidoctor_pdf_version
    value: '1.5.0.alpha.17'
  - name: asciidoctor_diagram_version
    value: '1.5.16'
  - name: asciidoctor_epub3_version
    value: '1.5.0.alpha.9'
  - name: asciidoctor_mathematical_version
    value: '0.3.0'
  - name: asciidoctor_revealjs_version
    value: '2.0.0'
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:1.12'
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 2
  triggers:
    - imageChange:
      type: ImageChange
    - type: ConfigChange
    - type: GitHub
      github:
        secretReference:
          name: github
